pipeline:
  build:
    image: docker
    commands:
      - docker build -t banjocat/jackmuratore:latest .
      - docker login -u banjocat -p ${DOCKER_PASS}
      - docker push banjocat/jackmuratore:latest

