pipeline:
  publish:
    image: plugins/docker
    email: jackmuratore@gmail.com
    repo: banjocat/jackmuratore
    tags: latest
    secrets:
      - docker_username
      - docker_password
  deploy:
    test:
    image: quay.io/honestbee/drone-kubernetes
    deployment: jackmuratore
    repo: banjocat/jackmuratore
    container: jackmuratore
    tag:                 
        - latest
    when:
        branch:
          - master


