pipeline:
  publish:
    image: plugins/docker
    email: jackmuratore@gmail.com
    repo: banjocat/jackmuratore
    tags: latest
    build_args:
      - "--cache-from banjocat/jackmuratore:latest"
    secrets:
      - docker_username
      - docker_password
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: jackmuratore-deployment
    repo: banjocat/jackmuratore
    container: jackmuratore
    tag:                 
        - latest
    when:
        branch:
          - master
    secrets:
      - KUBERNETES_CERT
      - KUBERNETES_SERVER
      - KUBERNETES_TOKEN


