apiVersion: v1
kind: Service
metadata:
  name: jackmuratore
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30008
  selector:
    app: jackmuratore
