---

- name: Install requirements
  apt: name={{item}}
  with_items:
      - apt-transport-https
      - ca-certificates
      - python-pip

- name: Add apt key
  apt_key:
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      id: "58118E89F3A912897C070ADBF76221572C52609D"

- name: Add source list
  apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"


- name: Purge old docker
  apt: name=lxc-docker state=absent


- name: Install docker
  apt: name=docker-engine

- name: Start docker
  service: name=docker state=started


- name: Install requirements for login
  pip: name={{item}}
  with_items:
      - docker-py


- name: Pull image
  docker_image:
      name: banjocat/jackmuratore

- name: Start container
  docker_container:
      name: jackmuratore
      image: banjocat/jackmuratore
      exposed_ports:
          - 8000
      ports:
          - "8100:8000"

